[project]
name = "dlt-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dlt[duckdb,parquet]>=1.5.0",
    "pandas>=2.2.3",
    "rich>=13.9.4",
    "typer>=0.15.1",
]
