name: Execute quick_start

on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * 1 *"
    # This runs at 10pm (UTC) every First day of month
  push:
    branches:
      - main
jobs:
  run_elt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v5
      - name: Install from uv.lock
        run: uv sync
      - name: Download parquet file and import to duckdb
        run: uv run quick_start.py
